const projects = [
  {
    title: "Fetch-master-6000",
    desc: "Simple Dilbert themed system information fetching tool for Linux and BSD based systems.",
    lang: "perl.png",
    codeberg: "https://codeberg.org/anhsirk0/fetch-master-6000",
    github: "https://github.com/anhsirk0/fetch-master-6000",
  },
  {
    title: "Undoo-Start",
    desc: "Super elegant startpage",
    lang: "rescript.png",
    codeberg: "https://codeberg.org/anhsirk0/undoo-start",
    github: "https://github.com/anhsirk0/undoo-start",
    url: "https://undoo.netlify.app",
  },
  {
    title: "Panda-Notes",
    desc: "Simple markdown notes",
    lang: "rescript.png",
    codeberg: "https://codeberg.org/anhsirk0/panda-notes",
    github: "https://github.com/anhsirk0/panda-notes",
    url: "https://notes-panda.netlify.app",
  },
  {
    title: "Landslides",
    desc: "Collection of Landing pages redesigned using DaisyUI",
    lang: "rescript.png",
    url: "https://landslides.netlify.app",
    codeberg: "https://codeberg.org/anhsirk0/landslides",
    github: "https://github.com/anhsirk0/landslides",
  },
  {
    title: "Whatsapp-svelte",
    desc: "WhatsApp mockup screens using Tailwind, DaisyUI and Sveltekit.",
    lang: "sveltekit.png",
    codeberg: "https://codeberg.org/anhsirk0/whatsapp-svelte",
    github: "https://github.com/anhsirk0/whatsapp-svelte",
    url: "https://anhsirk0.codeberg.page/whatsapp-svelte",
  },
  {
    title: "Local-notes",
    desc: "Sveltekit WebApp for managing notes locally without any backend.",
    lang: "sveltekit.png",
    codeberg: "https://codeberg.org/anhsirk0/local-notes",
    url: "https://anhsirk0.codeberg.page/local-notes",
  },
  {
    title: "Klip",
    desc: "Sveltekit WebApp for saving text for copy-pasting (clipboard).",
    lang: "sveltekit.png",
    codeberg: "https://codeberg.org/anhsirk0/klip",
    url: "https://anhsirk0.codeberg.page/klip",
  },
  {
    title: "Silver-Searcher",
    desc: "Svelte WebApp for searching same query on multiple sites.",
    lang: "sveltekit.png",
    codeberg: "https://codeberg.org/anhsirk0/silver-searcher",
    url: "https://anhsirk0.codeberg.page/silver-searcher",
  },
  {
    title: "Slider-login-signup",
    desc: "Login/Signup design with a slider animation made with tailwindcss and nextjs.",
    lang: "javascript.png",
    codeberg: "https://codeberg.org/anhsirk0/slider-login-signup",
    url: "https://anhsirk0-ts-projects.netlify.com/slider",
  },
  {
    title: "Tendrils",
    desc: "Markdown based social media platform. [React-Typescript]",
    lang: "react.png",
    codeberg: "https://codeberg.org/anhsirk0/tendrils-frontend",
    github: "https://github.com/anhsirk0/tendrils-frontend",
  },
  {
    title: "Tendrils-Backend",
    desc: "Backend for Markdown based social media platform. [Nestjs]",
    lang: "nestjs.png",
    codeberg: "https://codeberg.org/anhsirk0/tendrils-backend",
    github: "https://github.com/anhsirk0/tendrils-backend",
  },
  {
    title: "TS-projects",
    desc: "Some Typescript projects as NextJs pages.",
    lang: "typescript.png",
    codeberg: "https://codeberg.org/anhsirk0/ts-projects",
    url: "https://anhsirk0-ts-projects.netlify.com",
  },
  {
    title: "Gacp",
    desc: "Git add, commit and push in one go.",
    lang: "perl.png",
    codeberg: "https://codeberg.org/anhsirk0/gacp",
    github: "https://github.com/anhsirk0/gacp",
  },
  {
    title: "Arranger",
    desc: "Simple and capable Files and Directory arranger/cleaner.",
    lang: "perl.png",
    codeberg: "https://codeberg.org/anhsirk0/arng",
    github: "https://github.com/anhsirk0/file-arranger",
  },
  {
    title: "Pere",
    desc: "Pere is a bulk file renamer written in Perl.",
    lang: "perl.png",
    codeberg: "https://codeberg.org/anhsirk0/pere",
  },
  {
    title: "Notes-nestjs",
    desc: "Nestjs backend for simple notes management system.",
    lang: "nestjs.png",
    codeberg: "https://codeberg.org/anhsirk0/notes-nestjs",
  },
  {
    title: "Gacp-py",
    desc: "Python re-write of gacp (Git add, commit and push in one go).",
    lang: "python.png",
    codeberg: "https://codeberg.org/anhsirk0/gacp-py",
  },
  {
    title: "Alacritty-themes",
    desc: "Port of Modus-themes and Ef-themes for alacritty.",
    lang: "perl.png",
    codeberg: "https://codeberg.org/anhsirk0/alacritty-themes",
    github: "https://github.com/anhsirk0/alacritty-themes",
  },
  {
    title: "Wezterm-themes",
    desc: "Port of Modus-themes and Ef-themes for wezterm.",
    lang: "perl.png",
    codeberg: "https://codeberg.org/anhsirk0/wezterm-themes",
    github: "https://github.com/anhsirk0/wezterm-themes",
  },
  {
    title: "Kakoune-themes",
    desc: "Beautiful color schemes for kakoune text editor.",
    lang: "kakounescript",
    codeberg: "https://codeberg.org/anhsirk0/kakoune-themes",
    github: "https://github.com/anhsirk0/kakoune-themes",
  },
  {
    title: "Awesome-config",
    desc: "My config for the awesome window manager.",
    lang: "lua.png",
    codeberg: "https://codeberg.org/anhsirk0/awesome-config",
    github: "https://github.com/anhsirk0/awesome-config",
  },
  {
    title: "Rofi-config",
    desc: "Some cool scripts and Modus-themes & Ef-themes colors for rofi.",
    lang: "perl.png",
    codeberg: "https://codeberg.org/anhsirk0/rofi-config",
    github: "https://github.com/anhsirk0/rofi-config",
  },
  {
    title: "Mosaic-rust",
    desc: "Rust program to create photomosaics (image made of smaller images as mosaic tiles).",
    lang: "rust.png",
    codeberg: "https://codeberg.org/anhsirk0/mosaic-rust",
  },
  {
    title: "Lyapunov",
    desc: "Rust program to generate lyapunov fractals",
    lang: "rust.png",
    codeberg: "https://codeberg.org/anhsirk0/lyapunov",
  },
  {
    title: "Mandelbrot",
    desc: "Rust program to generate mandelbrot fractals",
    lang: "rust.png",
    codeberg: "https://codeberg.org/anhsirk0/mandelbrot",
  },
  {
    title: "Cellular-Automata",
    desc: "Elementary Cellular Automata implentation in Python. Print generations as graphs in the console.",
    lang: "python.png",
    codeberg: "https://codeberg.org/anhsirk0/cellular-automata",
  },
  {
    title: "Solus-awesome",
    desc: "Simple bash script to build & install awesomewm on Solus Linux.",
    lang: "bash.png",
    codeberg: "https://codeberg.org/anhsirk0/solus-awesome",
  },
  {
    title: "This website",
    desc: "Source code for this website. (anhsirk0.codeberg.page)",
    lang: "sveltekit.png",
    codeberg: "https://codeberg.org/anhsirk0/anhsirk0-sveltekit",
  },
];

export default projects;
